pluginManagement {
	repositories {

		maven {
			url "https://nexus-emea.1dc.com/repository/packages-nuxeo-com-maven-public"
		}
		maven {
			url 'https://nexus-emea.1dc.com/repository/jcenter-bintray-com'
		}
		maven {
			url 'https://nexus-emea.1dc.com/repository/gradle-plugin-mirror'
	 	}
		maven {
			url "https://nexus-emea.1dc.com/repository/de-esolutions-public/"
		}
		gradlePluginPortal()
		mavenCentral()
	}
}

plugins {
	id 'io.spring.develocity.conventions' version '0.0.22'
}

rootProject.name = 'spring-integration'

rootDir.eachDir { dir ->
	if (dir.name.startsWith('spring-integration-')) {
		include ":${dir.name}"
	}
}
